### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'exception'

### ISSUE THREAD

**Issue by ukanga** [onaio/mspray#489] opened 2018-12-06 08:06 UTC
https://sentry.onalabs.org/ona/mspray/issues/71928/

```
IntegrityError: null value in column "district_id" violates not-null constraint
DETAIL:  Failing row contains (674394, 36104577, null, {"_id": 36104577, "end": "2018-10-21T13:23:28.171+02", "date": "..., t, 2018-12-06 07:26:37.214467+00, 2018-12-06 07:26:37.214497+00, null, null, null, null).

  File "django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)

IntegrityError: null value in column "district_id" violates not-null constraint
DETAIL:  Failing row contains (674394, 36104577, null, {"_id": 36104577, "end": "2018-10-21T13:23:28.171+02", "date": "..., t, 2018-12-06 07:26:37.214467+00, 2018-12-06 07:26:37.214497+00, null, null, null, null).

(12 additional frame(s) were not displayed)
...
  File "django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)

AttributeError: 'Logger' object has no attribute 'exceprion'
  File "mspray/apps/main/tasks.py", line 743, in fetch_mobilisation
    logger.exceprion("{} Record not found.".format(formid))

AttributeError: 'Logger' object has no attribute 'exceprion'
```

**Comment by WinnyTroy** [comment] 2018-12-07 07:32
@moshthepitt this issue was caused by my accidental mispelling in this PR: #459.
Appologies.

Am going to close this issue as it was fixed by #491.

**Closed by WinnyTroy** 2018-12-07 07:32 UTC
